-- Databricks notebook source
-- MAGIC %md
-- MAGIC ## Creación de las tablas

-- COMMAND ----------

DROP TABLE IF EXISTS LINEITEM;
CREATE TABLE LINEITEM(
    L_ORDERKEY  INT
  ,  L_PARTKEY  INT
  ,  L_SUPPKEY  INT
  ,  L_LINENUMBER  INT
  ,  L_QUANTITY  FLOAT
  ,  L_EXTENDEDPRICE  FLOAT
  ,  L_DISCOUNT  FLOAT
  ,  L_TAX  FLOAT
  ,  L_RETURNFLAG  STRING
  ,  L_LINESTATUS  STRING
  ,  L_SHIPDATE  DATE
  ,  L_COMMITDATE  DATE
  ,  L_RECEIPTDATE  DATE
  ,  L_SHIPINSTRUCT  STRING
  ,  L_SHIPMODE  STRING
  ,  L_COMMENT  STRING
  )
USING csv
OPTIONS (
  PATH "/FileStore/shop/LINEITEM.csv",
  header true
);

DROP TABLE IF EXISTS NATION;
CREATE TABLE NATION(
  N_NATIONKEY INT
  , N_NAME STRING
  , N_REGIONKEY INT
  , N_COMMENT STRING)
USING csv
OPTIONS (
  PATH "/FileStore/shop/NATION.csv",
  header true
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS(
  O_ORDERKAY INT
  , O_CUSTKEY INT
  , O_ORDERSTATUS INT
  , O_TOTALPRICE FLOAT
  , O_ORDERDATE DATE
  , O_ORDERPRIORITY STRING
  , O_CLERK STRING
  , O_SHIPPRIORITY INT
  , O_COMMENT STRING)
USING csv
OPTIONS (
  PATH "/FileStore/shop/ORDERS.csv",
  header true
);

DROP TABLE IF EXISTS REGION;
CREATE TABLE REGION(
  R_REGIONKEY INT
  , R_NAME STRING
  , R_COMMENT STRING)
USING csv
OPTIONS (
  PATH "/FileStore/shop/REGION.csv",
  header true
);


DROP TABLE IF EXISTS SUPPLIER;
CREATE TABLE SUPPLIER(
  S_SUPPKEY INT
  , S_NAME STRING
  , S_ADDRESS STRING
  , S_NATIONKEY INT
  , S_PHONE STRING
  , S_ACCTBAL FLOAT
  , S_COMMENT STRING)
USING csv
OPTIONS (
  PATH "/FileStore/shop/SUPPLIER.csv",
  header true
);
